### ISSUE TITLE
Bad filament diameter?

### ISSUE THREAD

**Issue by raumin** [Eryone/STM32#2]
https://github.com/Eryone/STM32/blob/e86f76b1a9940dc69a85e2727c97255cfe52636c/Marlin_ER20/Marlin/Configuration.h#L148

Hi,
Is it normal that DEFAULT_NOMINAL_FILAMENT_DIA is set to 3.0 while this printer is a 1.75mm filament machine ?

**Comment by Eryone** [comment]
Hi, we have updated the config. Now it will show the correct one.
 And we need to point out this line will not affect the printing setting.
 Greeting
