### ISSUE TITLE
PID autotune freezes printer

### ISSUE THREAD

**Issue by sihawken** [Eryone/STM32#3]
I cannot run a PID autotune procedure with this printer. Both the LCD screen halts, and the serial communication stops.

edit: Specifically, this is for the ER20. I am using the latest version of the firmware, compiled from source here.

**Comment by Eryone** [comment]
It should be the printer motherboard problem.
On our test, it works.

Another user replaced it and it fixed.

**Comment by stormz85** [comment]
Hi !

when i do that my printer get freezed i have to reboot to use it
mother board was changed and the issue is still there.
Updated also with the marlin STM32 on the Eryone Github same issue.


Here is the command i use : M303 E0 S200 C8

**Comment by Dawood008** [comment]
Hi Storm, try to check firmware from this link = https://www.eryone.com/forum/viewtopic.php?f=6&t=439
Try PID after uploading the firmware, share details with us

**Comment by Eryone** [comment]
Hi, the PID freezes problem fixed at the new version of the firmware
2.0.8
You can go to download the new firmware and upload it.
