### ISSUE TITLE
Marlin command M117 seems to start Auto Bed Leveling on ER20

### ISSUE THREAD

**Issue by MacPro-de** [Eryone/STM32#5]
Hello, we used the firmware 2.0.5.3 from this Github page and tried the following with the prepared firmware as well as with a version, that we compiled by ourselves.
The printer is connected to a Raspberry Pi with Octoprint.
With both versions it happens, that, when we send a M117 command (Set LCD Message) via the terminal in Octoprint, then in 90% of the cases the printer starts the Auto Bed Leveling process (as we would have send a G29 command). In 5% of the cases nothing happens. Only in the other 5% the M117 command really displays our text on the LCD.
Is this a known issue? Any help would be much appreciated.

**Comment by ARM-Mac** [comment]
i have the same Problem.

**Comment by Eryone** [comment]
We have update the bug and now it fixed!
Thx!
